[package]
name = "rust_07_threads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.11.0"
resolve-path = "0.1.0"
slug = "0.1.5"
